version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: dupe_postgres
    environment:
      POSTGRES_USER: dupe_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: dupe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: